src/Cart/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('Cart', views.cart, name="cart"), 
    path('add_product/<int:pk>/', views.add_product, name='add_product'),
    path('remove_product/<int:pk>/', views.remove_product, name='remove_product'),
    path('decrement_product/<int:pk>/', views.decrement_product, name='decrement_product'),
    path('clear/', views.clear_cart, name='clear_cart'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/Productos/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('agregar_producto',views.agregar_producto,name="agregar_producto"),
    path('show_product/<str:pk>',views.show_product,name="show_product"),
    path('editar_producto/<str:pk>',views.editar_producto,name="editar_producto"),
    path('borrar_producto/<str:pk>',views.borrar_producto,name="borrar_producto"),
    path('search_categoria/',views.search_categoria, name='search_categoria'),
    path('search/',views.search, name='search'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/Users/urls.py
from django.urls import path
from . import views
from django.contrib.auth.views import LoginView, LogoutView
urlpatterns = [
    path('register/',views.registro,name="register"),
    path('login/',LoginView.as_view(template_name="login.html"),name="login"),
    path('logout/',LogoutView.as_view(template_name="logout.html"),name="logout"),
]

src/app/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import  TemplateView


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home,name="home"),
    path('Users/',include('Users.urls')),
    path('Productos/',include('Productos.urls')),
    path('Cart/',include('Cart.urls')),
    path('Nosotros',TemplateView.as_view(template_name="nosotros.html", extra_context={}), name="nosotros"),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/Cart/models.py
from django.db import models
from Productos.models import Producto

# Create your models here.

src/Productos/models.py
from django.db import models

# Create your models here.
STATUS_CHOICES = (
    ('Placa de Video', ('Placa de Video')),
    ('Procesador', ('Procesador')),
    ('Mouse', ('Mouse')),
    ('Teclado', ('Teclado')),
)
class Producto(models.Model):
    title = models.CharField(max_length=80)
    category = models.CharField(choices=STATUS_CHOICES, default="Placa de Video", max_length=15)
    imagen = models.ImageField(upload_to='productos',null=True,blank=True)
    description = models.TextField(max_length=155)
    precio = models.IntegerField(default=0)
    def __str__(self):
        return f'Producto: {self.title} | categoria: {self.category} | precio:{self.precio}'
    class Meta:
        ordering = ["-id"]

src/Users/models.py
from django.db import models

# Create your models here.

src/Cart/forms.py
from django import forms

src/Productos/forms.py
from django import forms
from .models import Producto
class ProductoForm(forms.ModelForm):
    class Meta:
        model = Producto
        fields = '__all__'

src/Users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class RegisterForm(UserCreationForm):
    email = forms.EmailField()
    password1 = forms.CharField(label="Contraseña", widget=forms.PasswordInput)
    password2 = forms.CharField(label="Confirmar Contraseña", widget=forms.PasswordInput)
    
    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']
        help_text = {k:"" for k in fields }

src/Cart/views.py
from django.shortcuts import render, redirect
from Productos.models import Producto
from django.contrib.auth.decorators import  login_required
from .cart import  Cart

def cart(request):
    return render(request,'Cart.html')


@login_required(login_url="login")
def add_product(request,pk):
    cart = Cart(request)
    product = Producto.objects.get( id = pk)
    cart.add(product = product)
    return redirect('cart')


@login_required(login_url="login")
def remove_product(request,pk):
    cart = Cart(request)
    product = Producto.objects.get( id = pk)
    cart.remove(product = product)
    return redirect('cart')


@login_required(login_url="login")
def decrement_product(request,pk):
    cart = Cart(request)
    product = Producto.objects.get( id = pk)
    cart.decrement(product = product)
    return redirect('cart')

@login_required(login_url="login")
def clear_cart(request):
    cart = Cart(request)
    cart.clear()
    return redirect('cart')

src/Productos/views.py
from django.shortcuts import render,redirect
from .forms import ProductoForm
from .models import Producto
from django.http import Http404
from django.contrib.admin.views.decorators import staff_member_required
# Create your views here.


@staff_member_required
def agregar_producto(request):
    form = ProductoForm()
    if request.method == "POST":
        form = ProductoForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            imagen = form.cleaned_data['imagen']
            return redirect('home')
        else:
            print(form.errors)
            raise Http404 
    context = {'form':form}
    return render(request,'agregar_producto.html',context)

def show_product(request,pk):
    prd = Producto.objects.get(id=pk)
    context = {'prd':prd}
    return render(request,'show_product.html',context)

@staff_member_required
def editar_producto(request, pk):
    
    tarea = Producto.objects.get(id=pk)
    form = ProductoForm(instance = tarea)

    if request.method == 'POST':
        form = ProductoForm(request.POST, instance = tarea)
        if form.is_valid():
            form.save()
            return redirect('/')

    context = {'form':form, 'tarea':tarea}
    return render(request,'editar_producto.html',context)

@staff_member_required
def borrar_producto(request,pk):
    prd = Producto.objects.get(id=pk)
    if request.method == 'POST':
        prd.delete()
        return redirect('home')

    context = {'prd':prd}
    return render(request,'borrar_producto.html',context)


def search(request):
    if request.method == "POST":
        busqueda = request.POST['busqueda']
        title_producto = Producto.objects.filter(title__contains = busqueda)
        description_producto = Producto.objects.filter(description__contains=busqueda)
        context ={
            'busqueda':busqueda,
            'title_producto':title_producto,
            'description_producto':description_producto,
            }
        return render(request,'search.html',context)
    else:
        context={}
        return render(request,'search.html',context)

def search_categoria(request):
    if request.method == "POST":
        busqueda = request.POST['busqueda']
        category_producto = Producto.objects.filter(category__contains=busqueda)
        context = {'busqueda':busqueda,'category_producto':category_producto}
        return render(request,'search.html',context)
    else:
        context={}
        return render(request,'search.html',context)

src/Users/views.py
from django.shortcuts import render, redirect
from .forms import RegisterForm
# Create your views here.


def registro(request):
    form = RegisterForm()
    if request.method == 'POST':
        form = RegisterForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            form.save()
            redirect('home')
    context = {'form': form}
    return render(request,'register.html',context)

src/app/views.py
from django.shortcuts import render
from Productos.models import Producto
from Cart.cart import Cart

def home(request):
    cart = Cart(request)
    product_main = Producto.objects.all()[0:3]
    product_secondary = Producto.objects.all()[3:10]
    context = {'product_main':product_main, 'product_secondary':product_secondary}
    return render(request,'home.html', context)

src/templates/Cart.html
{% extends 'layout/layout.html' %}
{% load static %}
{% load cart_tags %}
{% block link %}
<link href="{% static 'CSS/Cart.css' %}" rel="stylesheet" type="text/css">
{% endblock %}

{% block content %}
    <section>   
            {% if user.is_authenticated %}
                <span>{{user.username|upper}}</span>
            {% else %}
                <span>User</span>
            {% endif %}
            <ul>
                {% if request.session.cart.items %}
                    {% for key, value in request.session.cart.items %}
                        <li>
                            {{value.title}} 
                            <div class="separator"></div> 
                            <span><a href="{% url 'decrement_product' value.product_id %}"><i class='bx bx-minus'></i></a>
                                    {{value.quantity}}
                            <a href="{% url 'add_product' value.product_id %}"><i class='bx bx-plus'></i></a></span>
                            <div class="separator"></div>
                            $ {{value.precio|multiple:value.quantity}} 
                            <div class="separator"></div>
                            <a href="{% url 'remove_product' value.product_id %}"><i class='bx bxs-trash'></i></a>
                            <div class="separator"></div>  
                        </li>
                    {% endfor %}
                    <li class="section-lista-total">Total: $ {{cart_total_amout}}</li>
                {% else %}
                    <li>No hay items agregados</li>
                {% endif %}
            </ul>
            <a class="section-carrito-vaciar" href="{% url 'clear_cart' %}"> VACIAR CARRITO </a>
            <a class="section-carrito-comprar" href="#"> COMPRAR </a>
    </section>
{% endblock %}

src/templates/agregar_producto.html
{% extends 'layout/layout.html' %}

{% load static %}

{% block link %}
<link href="{% static 'CSS/agregar_producto.css'%}" rel="stylesheet" type="text/css">
{% endblock %}

{% block content %}
<section>
    <h2>Agregar Producto</h2>
    <form method="POST" enctype="multipart/form-data">{% csrf_token %}
        <label class="form-title-label" for="id_title">Titulo:</label>
        <input class="form-title-input"  type="text" name="title" maxlength="80" required="" id="id_title">
        <label class="form-category-label"  for="id_category">Categoria:</label>
        <select  class="form-category-input"  name="category" id="id_category">
            <option value="Placa de Video" selected="">Placa de Video</option>
          
            <option value="Procesador">Procesador</option>
          
            <option value="Mouse">Mouse</option>
          
            <option value="Teclado">Teclado</option>
          
        </select>
        <label  class="form-imagen-label"  for="id_imagen">Imagen:</label>
        <input class="form-imagen-input" type="file" name="imagen" accept="image/*" id="id_imagen">
        <label class="form-description-label" for="id_description">Description:</label>
        <textarea class="form-description-input" name="description" cols="40" rows="10" maxlength="155" required="" id="id_description"></textarea>
        <label class="form-precio-label" for="id_precio">Precio:  $</label>
        <input class="form-precio-input" type="number" name="precio" value="0" required="" id="id_precio">
        <button class="form-button-crear" type="submit">CREAR</button>
    </form>
</section>
{% endblock %}

src/templates/borrar_producto.html
{% extends 'layout/layout.html'%}
{% load static %}

{% block link %}
<link href="{% static 'CSS/borrar_producto.css'%}" rel="stylesheet" type="text/css">
{% endblock %}

{% block content %}

<section>
    <h2>¿Seguro que quiere eliminar el producto?</h2>
    <form method="POST">
        {% csrf_token %}
        <button type="submit">CONFIRMAR</button>
    </form>
    <a href="{% url 'home' %}">CANCELAR</a>

</section>

{% endblock %}

src/templates/editar_producto.html
{% extends 'layout/layout.html' %}
{% load static %}

{% block link %}
    <link href="{% static 'CSS/editar_producto.css' %}" rel="stylesheet" type="text/css">
{% endblock %}

{% block content %}
<section>
    <form method="POST" enctype="multipart/form-data">{% csrf_token %}
        <p class="form-title">{{form.title}}</p>
        <p class="form-categoria" > Categoria: {{form.category}}</p>
        <p class="form-image"><span>Imagen: </span><br>{{form.imagen}}</p>
        <p class="form-description">{{form.description}}</p>
        <p class="form-precio">Precio: ${{form.precio}}</p>
        <button type="submit">EDITAR</button>
        <a class="from-delete" href="{% url 'borrar_producto' tarea.id %}">BORRAR</a>
    </form>

</section>
{% endblock %}

src/templates/home.html
{% extends 'layout/layout.html'%}
{% load static %}
{% block link %}

<link href="{% static 'CSS/home.css' %}" rel="stylesheet" type="text/css"> 
{% endblock %}


{% block content %}
<section class="main-section-principal">
    {% for producto in  product_main %}
        <article> 
           <img src="{{producto.imagen.url}}">
           {% if user.is_staff %}
                <a href="{% url 'editar_producto' producto.id %}">Ver</a>
           {% else %}
                <a href="{% url 'show_product' producto.id %}">Ver</a>
            {% endif %}
        </article>
    {% endfor %}
</section>
<section class="main-section-secondary">
    <h2>Lista de Productos</h2>
    <ul>
        {% for producto2 in  product_secondary %}
            {% if user.is_staff %}
                <li><a href="{% url 'editar_producto' producto2.id %}">{{producto2.title}}: {{producto2.description}}</a></li>
            {% else %}
                <li><a href="{% url 'show_product' producto2.id %}">{{producto2.title}}: {{producto2.description}}</a></li>
            {% endif %}
        {% endfor %}

    </ul>
</section>
{% endblock %}

src/templates/layout/layout.html
{% load static %}

<!DOCTYPE html>
<html>
    <head>
        <title>MY WEB</title>
        <link href='https://unpkg.com/boxicons@2.0.8/css/boxicons.min.css' rel='stylesheet'>
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=DM+Sans:wght@500&display=swap" rel="stylesheet"> 
        <script src="{% static 'JS/menu.js' %}" defer></script>
        {% block link %}
        {% endblock %}
    </head>
    <body>
        <header>
            <img src="{% static 'IMG/logo.png'%}">
            <nav>

                {% if user.is_authenticated %} 
                    <a href="{% url 'logout'%}">LOG OUT</a>
                {% else %}
                    <a href="{% url 'login'%}">LOG IN</a>
                
                    <a href="{% url 'register'%}">REGISTER</a>

                {% endif %}
                {% if user.is_staff %} 

                {% else %}
                    <a href="{% url 'cart'%}">CARRITO</a>
                {% endif %}
            </nav>
            <button onclick="desplegarMenu()"><i class='bx bx-menu'></i></button>
        </header>
        
        <nav id="menu-hamburger-js" class="menu-hamburger">
            <a href="{% url 'home'%}">HOME</a>
            <div class="line"></div>
            <button onclick="desplegarCategorias()" id="btn-category-menu" class="desplegar-categorias">CATEGORIAS</button>
            <div class="line"></div>
            <a href="{% url 'nosotros' %}">NOSOTROS</a>
            <div class="line"></div>
            <a href="mailto:tomasfgraziano@hotmail.com">CONTACTO</a>
            <div class="line"></div>
            {% if user.is_staff %}
                <a class="new-product-mod" href="{% url 'agregar_producto' %}">+</a>
                <div class="line"></div>
            {% endif %}
            <form method="POST" action="{% url 'search' %}">{% csrf_token %}
                <input  type="search" placeholder="Search" aria-label="Search" name="busqueda">
                <button for="search" type="submit">BUSCAR</button>
            </form>
        </nav>
        <nav id="menu-category-js" class="menu-category">
            <button onclick="desplegarCategorias()"><i class='bx bx-left-arrow-alt'></i></button>
            <div class="line"></div>
            <form method="POST" action="{% url 'search_categoria' %}">{% csrf_token %}    
                <input style="display:none" value="Placa de Video" type="search" placeholder="Search" aria-label="Search" name="busqueda">
                <button type="submit">PLACA DE VIDEO</button>
            </form>
            <div class="line"></div>
            <form method="POST" action="{% url 'search_categoria' %}">{% csrf_token %}    
                <input style="display:none" value="Procesador" type="search" placeholder="Search" aria-label="Search" name="busqueda">
                <button type="submit">PROCESADOR</button>
            </form>
            <div class="line"></div>
            <form method="POST" action="{% url 'search_categoria' %}">{% csrf_token %}    
                <input style="display:none" value="Mouse" type="search" placeholder="Search" aria-label="Search" name="busqueda">
                <button type="submit">MOUSE</button>
            </form>
            <div class="line"></div>    
            <form method="POST" action="{% url 'search_categoria' %}">{% csrf_token %}    
                <input style="display:none" value="Teclado" type="search" placeholder="Search" aria-label="Search" name="busqueda">
                <button type="submit">TECLADO</button>
            </form>
        </nav>
        <main>
            {% block content %}

            {% endblock %}
        </main>
        <footer>
            <h2> ELECTRONIC APP</h2>
            <p>Graziano Tomas</p>
        </footer>
    </body>

</html>

src/templates/login.html
{% extends 'layout/layout.html' %}
{% load static %}

{% block link %}
<link href="{% static 'CSS/login.css'%}" rel="stylesheet" type="text/css">
{% endblock %}

{% block content %}
<section>
    <h2>Iniciar Sesion</h2>
    <form method="POST">{% csrf_token %}
        <label class="form-username-label" for="id_username">Username:</label>
        <input class="form-username-input" type="text" name="username" autofocus="" autocapitalize="none" autocomplete="username" maxlength="150" required="" id="id_username">
        <label class="form-password-label" for="id_password">Password:</label>
        <input class="form-password-input" type="password" name="password" autocomplete="current-password" required="" id="id_password">
        <button type="submit">INGRESAR</button>
    </form>
</section>
{% endblock %}

src/templates/logout.html
{% extends 'layout/layout.html' %}
{% load static %}

{% block link %}
<link href="{% static 'CSS/logout.css'%}" rel="stylesheet" type="text/css">
{% endblock %}

{% block content %}
<section>
    <h2>Te has Desconectado</h2>
</section>

{% endblock %}

src/templates/nosotros.html
{% extends 'layout/layout.html' %}
{% load static %}

{% block link %}
    <link href="{% static 'CSS/nosotros.css'%}" rel="stylesheet" type="text/css">
{% endblock %}

{% block content %}
<section>
    <h2>Nosotros</h2>
    <p>
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Molestias dicta dolorem aliquam, tempore vero mollitia modi obcaecati commodi non rem omnis fugiat pariatur incidunt ex accusamus in est voluptatibus sapiente.
        Unde ducimus et obcaecati temporibus corporis ex doloremque, quae iste quos perspiciatis officiis reiciendis nulla porro facilis aliquid quis. Veritatis tempora excepturi fugiat, totam ullam rem voluptate aperiam! Et, non!
        Doloribus at quos non officiis tenetur aut. Doloremque quidem dicta omnis aspernatur praesentium, ipsa similique minima explicabo optio, ut eos? Quis enim ullam animi facilis dolores impedit quidem ut totam.
        Quaerat amet quasi iste vitae, cupiditate aliquam culpa incidunt dolor numquam debitis reprehenderit voluptate illum! Eum possimus accusantium, et commodi voluptatem non laborum incidunt saepe, aut nesciunt soluta ad fuga.
        Nostrum aperiam corrupti beatae officiis nam! Modi, provident omnis praesentium eum qui, velit obcaecati libero natus vel necessitatibus vitae similique, reprehenderit ex doloribus sed nostrum consequatur tempore? Quas, sit error!
        Reiciendis aliquam aliquid, pariatur id perspiciatis quasi aut aperiam adipisci et maiores reprehenderit tempora possimus placeat eius error nostrum, animi dolor quisquam non, nam quae. Illum error possimus officia ipsum.
        Perspiciatis enim laboriosam odit quod debitis fuga maiores hic molestiae? Blanditiis recusandae totam laborum dolorem sit atque necessitatibus. Magni doloremque laudantium omnis, quos quasi at earum officiis sapiente praesentium repellendus!
        Totam quas minus quod eum nisi non placeat ducimus sit aperiam amet impedit, ad provident molestiae omnis dolor pariatur modi vero natus tempore maxime cumque illum itaque vel voluptatibus! Aut.

    </p>
    <img style="width:40px;" src="{% static 'IMG/logo.png' %}">
</section>
{% endblock %}

src/templates/register.html
{% extends 'layout/layout.html'%}
{% load static %}

{% block link %}
<link rel="stylesheet" type="text/css" href="{% static 'CSS/register.css'%}">
{% endblock %}


{% block content %}
<section>
    <h2>Registrarse</h2>
    <form method="POST">{% csrf_token %}
        <label class="username-label" for="id_username">Username:</label>
        <input class="username-input" type="text" name="username" maxlength="150" autofocus="" required="" id="id_username">
        <span class="helptext">Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.</span>
        <label class="email-label" for="id_email">Email:</label>
        <input class="email-input" type="email" name="email" required="" id="id_email">
        <label class="password1-label" for="id_password1">Contraseña:</label>
        <input class="password1-input" type="password" name="password1" required="" id="id_password1">
        <label class="password2-label" for="id_password2">Confirmar Contraseña:</label>
        <input class="password2-input" type="password" name="password2" required="" id="id_password2">
        <button type="submit">REGISTRARSE</button>
    </form>
</section>
{% endblock %}

src/templates/search.html
{% extends 'layout/layout.html' %}
{% load static %}

{% block link %}
<link href="{% static 'CSS/search.css'%}" rel="stylesheet" type="text/css">
{% endblock %}

{% block content %}
<section>
    {% if busqueda %}
    <h2>Lista de Productos: <span>{{busqueda|upper}} </span></h2>
    {% else %}
        <h2>No se ha realizado ninguna busqueda</h2>
    {% endif %}
    <ul>
        {% for prod_tit in title_producto %}
            <li><a href="{% url 'show_product' prod_tit.id %}">{{prod_tit.title}} | {{prod_tit.description}}</a></li>
        {% endfor %}
        {% for prod_descrip in description_producto %}
            <li><a href="{% url 'show_product' prod_descrip.id %}">{{prod_descrip.title}} |{{prod_tit.description}}</a></li>
        {% endfor %}
        {% for categoria in category_producto  %}
            <li><a href="{% url 'show_product' categoria.id %}">{{categoria.title}} | {{categoria.description}}</a></li>
        {% endfor %}
</section>
{% endblock %}

src/templates/show_product.html
{% extends 'layout/layout.html' %}
{% load static %}


{% block link %}
    <link href="{% static 'CSS/show_product.css' %}" rel="stylesheet" type="text/css">
{% endblock %}

{% block content %}
<section>
    <h2>{{prd.title}}</h2>
    <h3>{{prd.category}}</h3>
    <img src="{{prd.imagen.url}}">
    <p class="description">{{prd.description}}</p>
    <h3 class="precio-label">Precio: $</h3>
    <p class="precio-show">{{prd.precio}}</p>
    <a href="{% url 'add_product' prd.id %}">Añadir</a>
</section>
{% endblock %}